### ISSUE TITLE
Doesnt work in latest official version of Unity (v2019.1.0f2) 

### ISSUE THREAD

**Issue by guitarjorge24** [ejlv/UnityDarkThemePatch#6]
I have made sure that I have read/write permissions for the Unity.exe and I'm also running the patcher as admin. However, I get the following error when running it:
```
Unity binary: C:\Program Files\Unity\Hub\Editor\2019.1.0f2\Editor\Unity.exe
Patch status:
Unhandled Exception: System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at UnityDarkThemePatch.Patcher.ReadByteAtAddress(String filePath, Int64 address)
   at UnityDarkThemePatch.Patcher.GetPatchableByteValue()
   at UnityDarkThemePatch.Patcher.Init()
   at UnityDarkThemePatch.Program.Main()
```

I also tried SonicZentropy's branch which worked for Unity 2018 but it doesn't work for Unity 2019.

**Comment by guitarjorge24** [comment]
The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark

**Comment by Anax7** [comment]
Did you manage to fix it?

**Comment by guitarjorge24** [comment]
> 
> 
> Did you manage to fix it?

yes, just use a hex editor and change what I wrote

**Comment by TheSlippyPenguin** [comment]
https://github.com/ejlv/UnityDarkThemePatch/issues/6#issuecomment-485834148

Not working for macOS sadly

**Comment by TheSlippyPenguin** [comment]
Hex to change not working for macOS sadly

**Comment by Anax7** [comment]
I have applied the changes to the patcher and it works but I can't push as I don't have permission.

**Comment by Anax7** [comment]
I have made a fork here: https://github.com/Anax7/UnityDarkThemePatch

**Comment by guitarjorge24** [comment]
> 
> 
> I have made a fork here: https://github.com/Anax7/UnityDarkThemePatch

awesome, should be faster to use that next time

**Comment by TheSlippyPenguin** [comment]
> I have made a fork here: https://github.com/Anax7/UnityDarkThemePatch

Where is the executable ?

**Comment by guitarjorge24** [comment]
> 
> 
> > I have made a fork here: https://github.com/Anax7/UnityDarkThemePatch
> 
> Where is the executable ?

you can compile it yourself.

**Comment by Carbone313** [comment]
Hey, is there a way to get the dark theme with Linux ? (v. 2018.3.1f1)

**Comment by TheSlippyPenguin** [comment]
> > > I have made a fork here: https://github.com/Anax7/UnityDarkThemePatch
> > 
> > 
> > Where is the executable ?
> 
> you can compile it yourself.

or you can commit the executable ? I think it's easier for everyone

**Comment by TheSlippyPenguin** [comment]
Someone like Anax7 could commit it in a fork instead of letting users struggle with msbuild

**Comment by Anax7** [comment]
I have uploaded the executable, it's inside UnityDarkThemePatch folder.

**Comment by Xearoxde** [comment]
> I have uploaded the executable, it's inside UnityDarkThemePatch folder.

Your patcher doesn't work for me ... Unity is still in the light gray color. Don't know why.

Unity Version: Unity 2019.1.0f2 Personal

**Comment by Anax7** [comment]
It's not my patcher, I just made a fork & an update. Try that:
Step 1 : Open Regedit
Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
Step 3 : Ctrl+F type “UserSkin” hit enter
Step 4 : right click then modify value data from 0 to 1

**Comment by Xearoxde** [comment]
> It's not my patcher, I just made a fork & an update. Try that:
> 
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data from 0 to 1
> 
> They should give the dark skin free for all users, this is just ridiculous.

This does work! Thank you!

**Comment by TheSlippyPenguin** [comment]
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data from 0 to 1

Unable to find UserSkin... I start to think that Unity doesn't want me to keep my eyes working :(

**Comment by Schrodinger123** [comment]
> The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark

Any ideas about 2019.1.2f1 ?

**Comment by Xearoxde** [comment]
> > The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark
> 
> Any ideas about 2019.1.2f1 ?

I am still using 2019.1.1f1 ... 2019.1.3... ist already out but just no ... 1f1 works perfectly in darkmode.

**Comment by Schrodinger123** [comment]
> > > The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark
> > 
> > 
> > Any ideas about 2019.1.2f1 ?
> 
> I am still using 2019.1.1f1 ... 2019.1.3... ist already out but just no ... 1f1 works perfectly in darkmode.

Thx. I may gonna try this version tonight. Light mode are blinding me.

**Comment by SmashBoii** [comment]
> It's not my patcher, I just made a fork & an update. Try that:
> 
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data from 0 to 1
> 
> They should give the dark skin free for all users, this is just ridiculous.

Hey, it doesn't seem to find the "UserSkin" registery. I have followed carefully and I'm using the lates current Alpha of Unity (2019.3.0a5). Could you please help?

**Comment by Supergeek** [comment]
> The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark

Just used this patch successfully with 2019.1.8f1. The regular skin was making my eyes hurt after only 30 seconds of using 2019 after finally upgrading from 2018.

**Comment by Supergeek** [comment]
FYI Windows x64 2019.2.6f1:

00 75 15 33 C0 EB 13 90
replace with:
00 74 15 33 C0 EB 13 90

**Comment by xsilent007** [comment]
> 
> 
> FYI Windows x64 2019.2.6f1:
> 
> 00 75 15 33 C0 EB 13 90
> replace with:
> 00 74 15 33 C0 EB 13 90
> 
> Will upgrade when I actually go to release a game, but for now this saves me a lot of painful squinting. Bad UX, Unity.

Perfect, works with 2019.2.5f1!

**Comment by Keavon** [comment]
> > FYI Windows x64 2019.2.6f1:
> > 00 75 15 33 C0 EB 13 90
> > replace with:
> > 00 74 15 33 C0 EB 13 90
> > Will upgrade when I actually go to release a game, but for now this saves me a lot of painful squinting. Bad UX, Unity.
> 
> It's also work on 2019.2.10f1 too.
> Thanks a lot.

2019.3.0f3 works also! Patcher.cs is changed to declare these two variables now:

`public readonly byte[] RegionBytes = { 0x00, 0x75, 0x15, 0x33, 0xC0, 0xEB, 0x13, 0x90 };`

`public readonly int JumpInstructionOffset = 1;`
